# Generated by Django 5.0.1 on 2025-09-22 18:50

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoCafe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Tipo de Café',
                'verbose_name_plural': 'Tipos de Café',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Bodega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(choices=[('A', 'Bodega A'), ('B', 'Bodega B'), ('C', 'Bodega C'), ('D', 'Bodega D')], max_length=1, unique=True)),
                ('capacidad_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ubicacion', models.CharField(max_length=200)),
                ('responsable', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bodegas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='Lote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('peso_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('humedad', models.DecimalField(decimal_places=2, max_digits=5)),
                ('fecha_ingreso', models.DateTimeField(default=django.utils.timezone.now)),
                ('proveedor', models.CharField(max_length=200)),
                ('precio_quintal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('observaciones', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bodega', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lotes', to='beneficio.bodega')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lotes_creados', to=settings.AUTH_USER_MODEL)),
                ('tipo_cafe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lotes', to='beneficio.tipocafe')),
            ],
            options={
                'ordering': ['-fecha_ingreso'],
            },
        ),
        migrations.CreateModel(
            name='Mezcla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField(unique=True)),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('peso_total_kg', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('descripcion', models.TextField()),
                ('destino', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('responsable', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mezclas_responsables', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Procesado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_trilla', models.PositiveIntegerField()),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('peso_inicial_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('peso_final_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('catadura', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('rechazo_electronica', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('bajo_zaranda', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('barridos', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('observaciones', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='procesos', to='beneficio.lote')),
                ('operador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='procesos_operados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha'],
                'unique_together': {('lote', 'numero_trilla')},
            },
        ),
        migrations.CreateModel(
            name='DetalleMezcla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peso_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('porcentaje', models.DecimalField(decimal_places=2, max_digits=5)),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles_mezcla', to='beneficio.lote')),
                ('mezcla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='beneficio.mezcla')),
            ],
            options={
                'unique_together': {('mezcla', 'lote')},
            },
        ),
        migrations.CreateModel(
            name='Reproceso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField()),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('peso_inicial_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('peso_final_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('catadura', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('rechazo_electronica', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('bajo_zaranda', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('barridos', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('motivo', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('operador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reprocesos_operados', to=settings.AUTH_USER_MODEL)),
                ('procesado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reprocesos', to='beneficio.procesado')),
            ],
            options={
                'ordering': ['numero'],
                'unique_together': {('procesado', 'numero')},
            },
        ),
    ]
