# Generated by Django 5.0.1 on 2025-09-29 22:39

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficio', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Catacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_muestra', models.CharField(choices=[('lote', 'Lote'), ('procesado', 'Procesado/Trilla'), ('reproceso', 'Reproceso'), ('mezcla', 'Mezcla')], max_length=20)),
                ('codigo_muestra', models.CharField(max_length=50, unique=True)),
                ('fecha_catacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('peso_muestra_g', models.DecimalField(decimal_places=2, default=8.25, max_digits=5)),
                ('temperatura_agua', models.DecimalField(decimal_places=1, default=93.0, max_digits=4)),
                ('tiempo_infusion', models.IntegerField(default=4)),
                ('tipo_tueste', models.CharField(choices=[('claro', 'Claro (Agtron 65-75)'), ('medio', 'Medio (Agtron 55-65)'), ('oscuro', 'Oscuro (Agtron 45-55)')], default='medio', max_length=20)),
                ('humedad_grano', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('fragancia_aroma', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('sabor', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('sabor_residual', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('acidez', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('cuerpo', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('uniformidad', models.DecimalField(decimal_places=2, default=10, max_digits=4)),
                ('balance', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('taza_limpia', models.DecimalField(decimal_places=2, default=10, max_digits=4)),
                ('dulzor', models.DecimalField(decimal_places=2, default=10, max_digits=4)),
                ('puntaje_catador', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('puntaje_total', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('notas_positivas', models.TextField(blank=True)),
                ('notas_negativas', models.TextField(blank=True)),
                ('comentarios', models.TextField(blank=True)),
                ('clasificacion', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('catador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cataciones_realizadas', to=settings.AUTH_USER_MODEL)),
                ('lote', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cataciones', to='beneficio.lote')),
                ('mezcla', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cataciones', to='beneficio.mezcla')),
                ('procesado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cataciones', to='beneficio.procesado')),
                ('reproceso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cataciones', to='beneficio.reproceso')),
            ],
            options={
                'verbose_name': 'Catación',
                'verbose_name_plural': 'Cataciones',
                'ordering': ['-fecha_catacion'],
            },
        ),
        migrations.CreateModel(
            name='DefectoCatacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(choices=[('primario', 'Defecto Primario'), ('secundario', 'Defecto Secundario')], max_length=20)),
                ('tipo_defecto', models.CharField(max_length=50)),
                ('cantidad', models.IntegerField(default=0)),
                ('equivalente_defectos', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('catacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='defectos', to='beneficio.catacion')),
            ],
            options={
                'ordering': ['categoria', 'tipo_defecto'],
            },
        ),
    ]
