# Generated by Django 5.0.1 on 2025-09-30 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficio', '0002_catacion_defectocatacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='reproceso',
            name='nombre',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
