# Generated by Django 5.0.1 on 2025-10-02 17:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficio', '0003_reproceso_nombre'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='procesado',
            options={},
        ),
        migrations.AlterModelOptions(
            name='reproceso',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='procesado',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='reproceso',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='procesado',
            name='cafe_primera',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='procesado',
            name='cafe_segunda',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='procesado',
            name='unidad_cafe_primera',
            field=models.CharField(default='kg', max_length=20),
        ),
        migrations.AddField(
            model_name='procesado',
            name='unidad_cafe_segunda',
            field=models.CharField(default='kg', max_length=20),
        ),
        migrations.AddField(
            model_name='procesado',
            name='unidad_peso_final',
            field=models.CharField(default='kg', max_length=20),
        ),
        migrations.AddField(
            model_name='procesado',
            name='unidad_peso_inicial',
            field=models.CharField(default='kg', max_length=20),
        ),
        migrations.AddField(
            model_name='reproceso',
            name='cafe_primera',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='reproceso',
            name='cafe_segunda',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='reproceso',
            name='unidad_cafe_primera',
            field=models.CharField(default='kg', max_length=20),
        ),
        migrations.AddField(
            model_name='reproceso',
            name='unidad_cafe_segunda',
            field=models.CharField(default='kg', max_length=20),
        ),
        migrations.AddField(
            model_name='reproceso',
            name='unidad_peso_final',
            field=models.CharField(default='kg', max_length=20),
        ),
        migrations.AddField(
            model_name='reproceso',
            name='unidad_peso_inicial',
            field=models.CharField(default='kg', max_length=20),
        ),
        migrations.AlterField(
            model_name='procesado',
            name='numero_trilla',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='procesado',
            name='observaciones',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='procesado',
            name='operador',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='reproceso',
            name='operador',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='procesado',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='reproceso',
            name='created_at',
        ),
    ]
