# Generated by Django 5.0.1 on 2025-10-02 18:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficio', '0004_alter_procesado_options_alter_reproceso_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lote',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='lote',
            name='bodega',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beneficio.bodega'),
        ),
        migrations.AlterField(
            model_name='lote',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='lote',
            name='fecha_ingreso',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='lote',
            name='observaciones',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lote',
            name='tipo_cafe',
            field=models.CharField(max_length=100),
        ),
    ]
