# Generated by Django 5.0.1 on 2025-10-04 00:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beneficio', '0005_remove_lote_updated_at_alter_lote_bodega_and_more'),
    ]

    operations = [
    ]
