# Generated by Django 5.0.1 on 2025-10-04 15:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficio', '0006_auto_20251003_1841'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='procesado',
            options={'ordering': ['-fecha'], 'verbose_name': 'Procesado', 'verbose_name_plural': 'Procesados'},
        ),
        migrations.AlterModelOptions(
            name='reproceso',
            options={'ordering': ['-fecha']},
        ),
        migrations.AlterField(
            model_name='lote',
            name='bodega',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lotes', to='beneficio.bodega'),
        ),
    ]
