# Generated by Django 5.0.1 on 2025-11-10 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficio', '0007_alter_procesado_options_alter_reproceso_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catacion',
            name='codigo_muestra',
            field=models.CharField(editable=False, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='lote',
            name='codigo',
            field=models.CharField(editable=False, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='mezcla',
            name='numero',
            field=models.PositiveIntegerField(editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='procesado',
            name='numero_trilla',
            field=models.CharField(editable=False, max_length=50),
        ),
        migrations.AlterField(
            model_name='reproceso',
            name='numero',
            field=models.PositiveIntegerField(editable=False),
        ),
    ]
