# Generated by Django 5.0.1 on 2025-11-10 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficio', '0009_comprador_compra'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compra',
            name='registrado_por',
        ),
        migrations.AlterField(
            model_name='compra',
            name='estado_pago',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('parcial', 'Pago Parcial'), ('pagado', 'Pagado')], default='pendiente', max_length=20),
        ),
        migrations.AlterField(
            model_name='compra',
            name='metodo_pago',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='compra',
            name='monto_total',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=12),
        ),
        migrations.AlterField(
            model_name='compra',
            name='numero_factura',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
