# Generated by Django 5.0.1 on 2025-11-10 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficio', '0010_remove_compra_registrado_por_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mezcla',
            name='hora_final',
            field=models.TimeField(blank=True, null=True, verbose_name='Hora Final'),
        ),
        migrations.AddField(
            model_name='mezcla',
            name='hora_inicio',
            field=models.TimeField(blank=True, null=True, verbose_name='Hora de Inicio'),
        ),
        migrations.AddField(
            model_name='procesado',
            name='hora_final',
            field=models.TimeField(blank=True, null=True, verbose_name='Hora Final'),
        ),
        migrations.AddField(
            model_name='procesado',
            name='hora_inicio',
            field=models.TimeField(blank=True, null=True, verbose_name='Hora de Inicio'),
        ),
        migrations.AddField(
            model_name='reproceso',
            name='hora_final',
            field=models.TimeField(blank=True, null=True, verbose_name='Hora Final'),
        ),
        migrations.AddField(
            model_name='reproceso',
            name='hora_inicio',
            field=models.TimeField(blank=True, null=True, verbose_name='Hora de Inicio'),
        ),
    ]
