# Generated by Django 5.0.1 on 2025-11-10 22:27

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficio', '0011_mezcla_hora_final_mezcla_hora_inicio_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MantenimientoPlanta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horas_acumuladas', models.DecimalField(decimal_places=2, default=0, help_text='Horas acumuladas desde el último mantenimiento', max_digits=6)),
                ('limite_horas', models.DecimalField(decimal_places=2, default=40, help_text='Límite de horas antes del mantenimiento', max_digits=6)),
                ('estado', models.CharField(choices=[('operativa', 'Operativa'), ('requiere_mantenimiento', 'Requiere Mantenimiento'), ('en_mantenimiento', 'En Mantenimiento')], default='operativa', max_length=30)),
                ('ultimo_mantenimiento', models.DateTimeField(blank=True, null=True)),
                ('proximo_mantenimiento_estimado', models.DateTimeField(blank=True, null=True)),
                ('notas', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Control de Mantenimiento',
                'verbose_name_plural': 'Control de Mantenimiento',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HistorialMantenimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_mantenimiento', models.DateTimeField(default=django.utils.timezone.now)),
                ('horas_acumuladas', models.DecimalField(decimal_places=2, help_text='Horas acumuladas al momento del mantenimiento', max_digits=6)),
                ('tipo_mantenimiento', models.CharField(choices=[('preventivo', 'Preventivo'), ('correctivo', 'Correctivo'), ('emergencia', 'Emergencia')], default='preventivo', max_length=100)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('tiempo_mantenimiento_horas', models.DecimalField(decimal_places=2, default=0, help_text='Duración del mantenimiento', max_digits=5)),
                ('costo', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('realizado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mantenimientos_realizados', to=settings.AUTH_USER_MODEL)),
                ('control_mantenimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='beneficio.mantenimientoplanta')),
            ],
            options={
                'verbose_name': 'Historial de Mantenimiento',
                'verbose_name_plural': 'Historial de Mantenimientos',
                'ordering': ['-fecha_mantenimiento'],
            },
        ),
    ]
