# Generated by Django 5.0.1 on 2025-11-11 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficio', '0012_mantenimientoplanta_historialmantenimiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='reproceso',
            name='encargado_reproceso',
            field=models.CharField(blank=True, help_text='Persona a cargo del reproceso en piso', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='reproceso',
            name='hora_fin',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reproceso',
            name='hora_inicio',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
