# Generated by Django 5.0.1 on 2025-11-12 15:13

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficio', '0013_reproceso_encargado_reproceso_reproceso_hora_fin_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReciboCafe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_recibo', models.CharField(editable=False, max_length=50, unique=True)),
                ('fecha_recibo', models.DateTimeField(default=django.utils.timezone.now)),
                ('peso', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unidad', models.CharField(choices=[('kg', 'Kilogramos'), ('qq', 'Quintales'), ('lb', 'Libras')], default='qq', max_length=10)),
                ('humedad', models.DecimalField(decimal_places=2, help_text='Porcentaje de humedad', max_digits=5)),
                ('proveedor', models.CharField(max_length=200)),
                ('precio_quintal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('monto_total', models.DecimalField(decimal_places=2, editable=False, max_digits=12)),
                ('numero_boletas', models.IntegerField(default=0, help_text='Número de boletas/sacos')),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recibos', to='beneficio.lote')),
                ('registrado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recibos_registrados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Recibo de Café',
                'verbose_name_plural': 'Recibos de Café',
                'ordering': ['-fecha_recibo'],
            },
        ),
    ]
