# Generated by Django 5.0.1 on 2025-11-13 15:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficio', '0014_recibocafe'),
    ]

    operations = [
        migrations.AddField(
            model_name='procesado',
            name='recibo',
            field=models.ForeignKey(blank=True, help_text='Recibo específico del cual proviene este procesado', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='procesamientos', to='beneficio.recibocafe'),
        ),
        migrations.AddField(
            model_name='recibocafe',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('proceso_parcial', 'Proceso Parcial'), ('procesado_completo', 'Procesado Completo')], default='pendiente', max_length=20),
        ),
        migrations.AddField(
            model_name='recibocafe',
            name='peso_procesado',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='recibocafe',
            name='humedad',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='recibocafe',
            name='monto_total',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12),
        ),
        migrations.AlterField(
            model_name='recibocafe',
            name='numero_boletas',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
