# Generated by Django 5.0.1 on 2025-11-13 22:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficio', '0015_procesado_recibo_recibocafe_estado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procesado',
            name='recibo',
            field=models.ForeignKey(blank=True, help_text='Recibo específico del cual proviene este procesado', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='procesos_realizados', to='beneficio.recibocafe'),
        ),
    ]
