# Generated by Django 5.0.1 on 2025-11-17 21:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficio', '0016_alter_procesado_recibo'),
    ]

    operations = [
        migrations.AddField(
            model_name='mezcla',
            name='bodega_destino',
            field=models.ForeignKey(blank=True, help_text='Bodega donde se almacenó la mezcla de café', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mezclas_almacenadas', to='beneficio.bodega', verbose_name='Bodega de Almacenamiento'),
        ),
        migrations.AddField(
            model_name='procesado',
            name='bodega_destino',
            field=models.ForeignKey(blank=True, help_text='Bodega donde se almacenó el café después del procesado', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='procesados_almacenados', to='beneficio.bodega', verbose_name='Bodega de Almacenamiento'),
        ),
        migrations.AddField(
            model_name='reproceso',
            name='bodega_destino',
            field=models.ForeignKey(blank=True, help_text='Bodega donde se almacenó el café después del reproceso', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reprocesos_almacenados', to='beneficio.bodega', verbose_name='Bodega de Almacenamiento'),
        ),
    ]
