# Generated by Django 5.0.1 on 2025-11-17 21:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficio', '0017_mezcla_bodega_destino_procesado_bodega_destino_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mezcla',
            name='bodega_destino',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mezclas_almacenadas', to='beneficio.bodega', verbose_name='Bodega de Almacenamiento'),
        ),
        migrations.AlterField(
            model_name='procesado',
            name='bodega_destino',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='procesados_almacenados', to='beneficio.bodega', verbose_name='Bodega de Almacenamiento'),
        ),
        migrations.AlterField(
            model_name='reproceso',
            name='bodega_destino',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reprocesos_almacenados', to='beneficio.bodega', verbose_name='Bodega de Almacenamiento'),
        ),
    ]
