# Generated by Django 5.0.1 on 2025-11-19 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficio', '0018_alter_mezcla_bodega_destino_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='procesado',
            name='peso_saco_referencia',
            field=models.DecimalField(decimal_places=2, default=69, help_text='Peso de referencia para calcular sacos', max_digits=6),
        ),
        migrations.AddField(
            model_name='procesado',
            name='unidad_saco_referencia',
            field=models.CharField(choices=[('kg', 'Kilogramos'), ('lb', 'Libras')], default='kg', help_text='Unidad del peso de referencia', max_length=10),
        ),
        migrations.AddField(
            model_name='reproceso',
            name='peso_saco_referencia',
            field=models.DecimalField(decimal_places=2, default=69, help_text='Peso de referencia para calcular sacos', max_digits=6),
        ),
        migrations.AddField(
            model_name='reproceso',
            name='unidad_saco_referencia',
            field=models.CharField(choices=[('kg', 'Kilogramos'), ('lb', 'Libras')], default='kg', max_length=10),
        ),
    ]
