# Generated by Django 5.0.1 on 2025-11-19 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficio', '0019_procesado_peso_saco_referencia_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='procesado',
            name='peso_saco_referencia',
        ),
        migrations.RemoveField(
            model_name='procesado',
            name='unidad_saco_referencia',
        ),
        migrations.RemoveField(
            model_name='reproceso',
            name='hora_fin',
        ),
        migrations.RemoveField(
            model_name='reproceso',
            name='peso_saco_referencia',
        ),
        migrations.RemoveField(
            model_name='reproceso',
            name='unidad_saco_referencia',
        ),
        migrations.AlterField(
            model_name='reproceso',
            name='hora_inicio',
            field=models.TimeField(blank=True, null=True, verbose_name='Hora de Inicio'),
        ),
    ]
