# Generated by Django 5.0.1 on 2025-11-26 15:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficio', '0020_remove_procesado_peso_saco_referencia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='catacion',
            name='actividad_agua',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Actividad de Agua'),
        ),
        migrations.AddField(
            model_name='catacion',
            name='altitud',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Altitud'),
        ),
        migrations.AddField(
            model_name='catacion',
            name='attr_acido_fermentado',
            field=models.BooleanField(default=False, verbose_name='Ácido/Fermentado'),
        ),
        migrations.AddField(
            model_name='catacion',
            name='attr_afrutado',
            field=models.BooleanField(default=False, verbose_name='Afrutado'),
        ),
        migrations.AddField(
            model_name='catacion',
            name='attr_dulce',
            field=models.BooleanField(default=False, verbose_name='Dulce'),
        ),
        migrations.AddField(
            model_name='catacion',
            name='attr_especias',
            field=models.BooleanField(default=False, verbose_name='Especias'),
        ),
        migrations.AddField(
            model_name='catacion',
            name='attr_floral',
            field=models.BooleanField(default=False, verbose_name='Floral'),
        ),
        migrations.AddField(
            model_name='catacion',
            name='attr_nueces_cacao',
            field=models.BooleanField(default=False, verbose_name='Nueces/Cacao'),
        ),
        migrations.AddField(
            model_name='catacion',
            name='attr_tostado',
            field=models.BooleanField(default=False, verbose_name='Tostado'),
        ),
        migrations.AddField(
            model_name='catacion',
            name='attr_verde_vegetal',
            field=models.BooleanField(default=False, verbose_name='Verde/Vegetal'),
        ),
        migrations.AddField(
            model_name='catacion',
            name='color_amarillo',
            field=models.BooleanField(default=False, verbose_name='Amarillo'),
        ),
        migrations.AddField(
            model_name='catacion',
            name='color_amarillo_verdoso',
            field=models.BooleanField(default=False, verbose_name='Amarillo Verdoso'),
        ),
        migrations.AddField(
            model_name='catacion',
            name='color_azul_verde',
            field=models.BooleanField(default=False, verbose_name='Azul Verde'),
        ),
        migrations.AddField(
            model_name='catacion',
            name='color_cafe',
            field=models.BooleanField(default=False, verbose_name='Café'),
        ),
        migrations.AddField(
            model_name='catacion',
            name='color_otro',
            field=models.BooleanField(default=False, verbose_name='Otro'),
        ),
        migrations.AddField(
            model_name='catacion',
            name='color_verde',
            field=models.BooleanField(default=False, verbose_name='Verde'),
        ),
        migrations.AddField(
            model_name='catacion',
            name='color_verde_amarillento',
            field=models.BooleanField(default=False, verbose_name='Verde Amarillento'),
        ),
        migrations.AddField(
            model_name='catacion',
            name='color_verde_azulado',
            field=models.BooleanField(default=False, verbose_name='Verde Azulado'),
        ),
        migrations.AddField(
            model_name='catacion',
            name='cuerpo_aceitoso',
            field=models.BooleanField(default=False, verbose_name='Aceitoso'),
        ),
        migrations.AddField(
            model_name='catacion',
            name='cuerpo_aspero',
            field=models.BooleanField(default=False, verbose_name='Áspero'),
        ),
        migrations.AddField(
            model_name='catacion',
            name='cuerpo_metalico',
            field=models.BooleanField(default=False, verbose_name='Metálico'),
        ),
        migrations.AddField(
            model_name='catacion',
            name='cuerpo_seca_boca',
            field=models.BooleanField(default=False, verbose_name='Seca Boca'),
        ),
        migrations.AddField(
            model_name='catacion',
            name='cuerpo_suave',
            field=models.BooleanField(default=False, verbose_name='Suave'),
        ),
        migrations.AddField(
            model_name='catacion',
            name='defectos_intensidad_2',
            field=models.IntegerField(default=0, verbose_name='Defectos Intensidad 2'),
        ),
        migrations.AddField(
            model_name='catacion',
            name='defectos_intensidad_4',
            field=models.IntegerField(default=0, verbose_name='Defectos Intensidad 4'),
        ),
        migrations.AddField(
            model_name='catacion',
            name='descripcion_defectos',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción de Defectos'),
        ),
        migrations.AddField(
            model_name='catacion',
            name='finca',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Finca'),
        ),
        migrations.AddField(
            model_name='catacion',
            name='gran_10',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Tamaño 10'),
        ),
        migrations.AddField(
            model_name='catacion',
            name='gran_11',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Tamaño 11'),
        ),
        migrations.AddField(
            model_name='catacion',
            name='gran_12',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Tamaño 12'),
        ),
        migrations.AddField(
            model_name='catacion',
            name='gran_13',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Tamaño 13'),
        ),
        migrations.AddField(
            model_name='catacion',
            name='gran_14',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Tamaño 14'),
        ),
        migrations.AddField(
            model_name='catacion',
            name='gran_15',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Tamaño 15'),
        ),
        migrations.AddField(
            model_name='catacion',
            name='gran_16',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Tamaño 16'),
        ),
        migrations.AddField(
            model_name='catacion',
            name='gran_17',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Tamaño 17'),
        ),
        migrations.AddField(
            model_name='catacion',
            name='gran_18',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Tamaño 18'),
        ),
        migrations.AddField(
            model_name='catacion',
            name='gran_19',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Tamaño 19'),
        ),
        migrations.AddField(
            model_name='catacion',
            name='gran_20',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Tamaño 20'),
        ),
        migrations.AddField(
            model_name='catacion',
            name='gran_21',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Tamaño 21'),
        ),
        migrations.AddField(
            model_name='catacion',
            name='gusto_acido',
            field=models.BooleanField(default=False, verbose_name='Ácido'),
        ),
        migrations.AddField(
            model_name='catacion',
            name='gusto_amargo',
            field=models.BooleanField(default=False, verbose_name='Amargo'),
        ),
        migrations.AddField(
            model_name='catacion',
            name='gusto_dulce',
            field=models.BooleanField(default=False, verbose_name='Dulce'),
        ),
        migrations.AddField(
            model_name='catacion',
            name='gusto_salado',
            field=models.BooleanField(default=False, verbose_name='Salado'),
        ),
        migrations.AddField(
            model_name='catacion',
            name='gusto_umami',
            field=models.BooleanField(default=False, verbose_name='Umami'),
        ),
        migrations.AddField(
            model_name='catacion',
            name='horas_fermentacion',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Horas Fermentación'),
        ),
        migrations.AddField(
            model_name='catacion',
            name='intensidad_acidez',
            field=models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Intensidad Acidez'),
        ),
        migrations.AddField(
            model_name='catacion',
            name='intensidad_aroma',
            field=models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Intensidad Aroma'),
        ),
        migrations.AddField(
            model_name='catacion',
            name='intensidad_cuerpo',
            field=models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Intensidad Cuerpo'),
        ),
        migrations.AddField(
            model_name='catacion',
            name='intensidad_fragancia',
            field=models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Intensidad Fragancia'),
        ),
        migrations.AddField(
            model_name='catacion',
            name='intensidad_sabor',
            field=models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Intensidad Sabor'),
        ),
        migrations.AddField(
            model_name='catacion',
            name='intensidad_sabor_residual',
            field=models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Intensidad Sabor Residual'),
        ),
        migrations.AddField(
            model_name='catacion',
            name='notas_acidez',
            field=models.TextField(blank=True, null=True, verbose_name='Notas Acidez'),
        ),
        migrations.AddField(
            model_name='catacion',
            name='notas_acidez_afectivo',
            field=models.TextField(blank=True, null=True, verbose_name='Notas Acidez'),
        ),
        migrations.AddField(
            model_name='catacion',
            name='notas_aroma',
            field=models.TextField(blank=True, null=True, verbose_name='Notas Aroma'),
        ),
        migrations.AddField(
            model_name='catacion',
            name='notas_balance',
            field=models.TextField(blank=True, null=True, verbose_name='Notas Balance'),
        ),
        migrations.AddField(
            model_name='catacion',
            name='notas_catador',
            field=models.TextField(blank=True, null=True, verbose_name='Notas del Catador'),
        ),
        migrations.AddField(
            model_name='catacion',
            name='notas_cuerpo',
            field=models.TextField(blank=True, null=True, verbose_name='Notas Cuerpo'),
        ),
        migrations.AddField(
            model_name='catacion',
            name='notas_cuerpo_afectivo',
            field=models.TextField(blank=True, null=True, verbose_name='Notas Cuerpo'),
        ),
        migrations.AddField(
            model_name='catacion',
            name='notas_extrinseca',
            field=models.TextField(blank=True, null=True, verbose_name='Notas Extrínsecas'),
        ),
        migrations.AddField(
            model_name='catacion',
            name='notas_fragancia',
            field=models.TextField(blank=True, null=True, verbose_name='Notas Fragancia'),
        ),
        migrations.AddField(
            model_name='catacion',
            name='notas_fragancia_aroma',
            field=models.TextField(blank=True, null=True, verbose_name='Notas Fragancia/Aroma'),
        ),
        migrations.AddField(
            model_name='catacion',
            name='notas_general',
            field=models.TextField(blank=True, null=True, verbose_name='Notas General'),
        ),
        migrations.AddField(
            model_name='catacion',
            name='notas_perfil',
            field=models.TextField(blank=True, null=True, verbose_name='Notas Perfil'),
        ),
        migrations.AddField(
            model_name='catacion',
            name='notas_residual',
            field=models.TextField(blank=True, null=True, verbose_name='Notas Residual'),
        ),
        migrations.AddField(
            model_name='catacion',
            name='notas_residual_afectivo',
            field=models.TextField(blank=True, null=True, verbose_name='Notas Residual'),
        ),
        migrations.AddField(
            model_name='catacion',
            name='notas_sabor',
            field=models.TextField(blank=True, null=True, verbose_name='Notas Sabor'),
        ),
        migrations.AddField(
            model_name='catacion',
            name='notas_sabor_afectivo',
            field=models.TextField(blank=True, null=True, verbose_name='Notas Sabor'),
        ),
        migrations.AddField(
            model_name='catacion',
            name='observaciones_granulometria',
            field=models.TextField(blank=True, null=True, verbose_name='Observaciones Granulometría'),
        ),
        migrations.AddField(
            model_name='catacion',
            name='peso_muestra_granulometria',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Peso Muestra (g)'),
        ),
        migrations.AddField(
            model_name='catacion',
            name='proceso',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Proceso'),
        ),
        migrations.AddField(
            model_name='catacion',
            name='productor',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Productor'),
        ),
        migrations.AddField(
            model_name='catacion',
            name='region',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Región'),
        ),
        migrations.AddField(
            model_name='catacion',
            name='secado',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Secado'),
        ),
        migrations.AddField(
            model_name='catacion',
            name='variedad',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Variedad'),
        ),
    ]
