# Generated by Django 5.0.1 on 2025-11-26 16:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficio', '0021_catacion_actividad_agua_catacion_altitud_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catacion',
            name='intensidad_acidez',
            field=models.DecimalField(decimal_places=1, default=5, max_digits=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Intensidad Acidez'),
        ),
        migrations.AlterField(
            model_name='catacion',
            name='intensidad_aroma',
            field=models.DecimalField(decimal_places=1, default=5, max_digits=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Intensidad Aroma'),
        ),
        migrations.AlterField(
            model_name='catacion',
            name='intensidad_cuerpo',
            field=models.DecimalField(decimal_places=1, default=5, max_digits=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Intensidad Cuerpo'),
        ),
        migrations.AlterField(
            model_name='catacion',
            name='intensidad_fragancia',
            field=models.DecimalField(decimal_places=1, default=5, max_digits=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Intensidad Fragancia'),
        ),
        migrations.AlterField(
            model_name='catacion',
            name='intensidad_sabor',
            field=models.DecimalField(decimal_places=1, default=5, max_digits=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Intensidad Sabor'),
        ),
        migrations.AlterField(
            model_name='catacion',
            name='intensidad_sabor_residual',
            field=models.DecimalField(decimal_places=1, default=5, max_digits=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Intensidad Sabor Residual'),
        ),
    ]
