# Generated by Django 5.0.1 on 2025-12-01 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficio', '0022_alter_catacion_intensidad_acidez_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='procesado',
            name='finalizado',
            field=models.BooleanField(default=False, help_text='Indica si el procesado ha sido completado'),
        ),
    ]
