# Generated by Django 5.0.1 on 2025-12-02 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficio', '0023_procesado_finalizado'),
    ]

    operations = [
        migrations.AddField(
            model_name='catacion',
            name='defecto_acido_parcial_count',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Ácido Parcial - Cuenta'),
        ),
        migrations.AddField(
            model_name='catacion',
            name='defecto_acido_parcial_full',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Ácido Parcial - Completo'),
        ),
        migrations.AddField(
            model_name='catacion',
            name='defecto_acido_total_count',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Ácido Total - Cuenta'),
        ),
        migrations.AddField(
            model_name='catacion',
            name='defecto_acido_total_full',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Ácido Total - Completo'),
        ),
        migrations.AddField(
            model_name='catacion',
            name='defecto_cascara_count',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Cáscara - Cuenta'),
        ),
        migrations.AddField(
            model_name='catacion',
            name='defecto_cascara_full',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Cáscara - Completo'),
        ),
        migrations.AddField(
            model_name='catacion',
            name='defecto_cereza_seca_count',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Cereza Seca - Cuenta'),
        ),
        migrations.AddField(
            model_name='catacion',
            name='defecto_cereza_seca_full',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Cereza Seca - Completo'),
        ),
        migrations.AddField(
            model_name='catacion',
            name='defecto_concha_count',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Concha - Cuenta'),
        ),
        migrations.AddField(
            model_name='catacion',
            name='defecto_concha_full',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Concha - Completo'),
        ),
        migrations.AddField(
            model_name='catacion',
            name='defecto_dano_count',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Daño - Cuenta'),
        ),
        migrations.AddField(
            model_name='catacion',
            name='defecto_dano_full',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Daño - Completo'),
        ),
        migrations.AddField(
            model_name='catacion',
            name='defecto_dano_leve_count',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Daño Leve - Cuenta'),
        ),
        migrations.AddField(
            model_name='catacion',
            name='defecto_dano_leve_full',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Daño Leve - Completo'),
        ),
        migrations.AddField(
            model_name='catacion',
            name='defecto_dano_severo_count',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Daño Severo - Cuenta'),
        ),
        migrations.AddField(
            model_name='catacion',
            name='defecto_dano_severo_full',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Daño Severo - Completo'),
        ),
        migrations.AddField(
            model_name='catacion',
            name='defecto_fenolico',
            field=models.BooleanField(default=False, verbose_name='Defecto Fenólico'),
        ),
        migrations.AddField(
            model_name='catacion',
            name='defecto_flotador_count',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Flotador - Cuenta'),
        ),
        migrations.AddField(
            model_name='catacion',
            name='defecto_flotador_full',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Flotador - Completo'),
        ),
        migrations.AddField(
            model_name='catacion',
            name='defecto_hongos_count',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Hongos - Cuenta'),
        ),
        migrations.AddField(
            model_name='catacion',
            name='defecto_hongos_full',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Hongos - Completo'),
        ),
        migrations.AddField(
            model_name='catacion',
            name='defecto_inmaduro_count',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Inmaduro/Verde - Cuenta'),
        ),
        migrations.AddField(
            model_name='catacion',
            name='defecto_inmaduro_full',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Inmaduro/Verde - Completo'),
        ),
        migrations.AddField(
            model_name='catacion',
            name='defecto_insectos_count',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Insectos - Cuenta'),
        ),
        migrations.AddField(
            model_name='catacion',
            name='defecto_insectos_full',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Insectos - Completo'),
        ),
        migrations.AddField(
            model_name='catacion',
            name='defecto_marchitado_count',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Marchitado - Cuenta'),
        ),
        migrations.AddField(
            model_name='catacion',
            name='defecto_marchitado_full',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Marchitado - Completo'),
        ),
        migrations.AddField(
            model_name='catacion',
            name='defecto_materia_extrana_count',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Materia Extraña - Cuenta'),
        ),
        migrations.AddField(
            model_name='catacion',
            name='defecto_materia_extrana_full',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Materia Extraña - Completo'),
        ),
        migrations.AddField(
            model_name='catacion',
            name='defecto_mohoso',
            field=models.BooleanField(default=False, verbose_name='Defecto Mohoso'),
        ),
        migrations.AddField(
            model_name='catacion',
            name='defecto_negro_parcial_count',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Negro Parcial - Cuenta'),
        ),
        migrations.AddField(
            model_name='catacion',
            name='defecto_negro_parcial_full',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Negro Parcial - Completo'),
        ),
        migrations.AddField(
            model_name='catacion',
            name='defecto_negro_total_count',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Negro Total - Cuenta'),
        ),
        migrations.AddField(
            model_name='catacion',
            name='defecto_negro_total_full',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Negro Total - Completo'),
        ),
        migrations.AddField(
            model_name='catacion',
            name='defecto_papa',
            field=models.BooleanField(default=False, verbose_name='Defecto Papa'),
        ),
        migrations.AddField(
            model_name='catacion',
            name='defecto_pergamino_count',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Pergamino - Cuenta'),
        ),
        migrations.AddField(
            model_name='catacion',
            name='defecto_pergamino_full',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Pergamino - Completo'),
        ),
        migrations.AddField(
            model_name='catacion',
            name='defecto_rotos_count',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Rotos/Astillados - Cuenta'),
        ),
        migrations.AddField(
            model_name='catacion',
            name='defecto_rotos_full',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Rotos/Astillados - Completo'),
        ),
        migrations.AddField(
            model_name='catacion',
            name='tazas_defectuosas',
            field=models.PositiveIntegerField(default=0, verbose_name='Tazas Defectuosas'),
        ),
        migrations.AddField(
            model_name='catacion',
            name='tazas_no_uniformes',
            field=models.PositiveIntegerField(default=0, verbose_name='Tazas No Uniformes'),
        ),
        migrations.AddField(
            model_name='catacion',
            name='total_defectos_cat1',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Total Defectos Categoría 1'),
        ),
        migrations.AddField(
            model_name='catacion',
            name='total_defectos_cat2',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Total Defectos Categoría 2'),
        ),
        migrations.AddField(
            model_name='catacion',
            name='total_green_defects',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Total Green Defects'),
        ),
    ]
