# Generated by Django 5.0.1 on 2025-12-02 21:53

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficio', '0024_catacion_defecto_acido_parcial_count_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exportacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_exportacion', models.CharField(editable=False, max_length=50, unique=True)),
                ('fecha_exportacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('estado', models.CharField(choices=[('preparacion', 'En Preparación'), ('documentacion', 'Documentación en Proceso'), ('transito', 'En Tránsito'), ('entregada', 'Entregada'), ('cancelada', 'Cancelada')], default='preparacion', max_length=20)),
                ('tipo_producto', models.CharField(choices=[('procesado', 'Procesado/Trilla'), ('reproceso', 'Reproceso'), ('mezcla', 'Mezcla')], max_length=20)),
                ('pais_destino', models.CharField(max_length=100)),
                ('ciudad_destino', models.CharField(blank=True, max_length=100, null=True)),
                ('peso_exportado_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precio_quintal', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio por Quintal (Q)')),
                ('precio_total', models.DecimalField(decimal_places=2, editable=False, max_digits=12)),
                ('numero_contenedor', models.CharField(blank=True, max_length=100, null=True)),
                ('numero_bl', models.CharField(blank=True, max_length=100, null=True, verbose_name='Bill of Lading')),
                ('numero_factura', models.CharField(blank=True, max_length=100, null=True)),
                ('certificado_origen', models.CharField(blank=True, max_length=100, null=True)),
                ('tipo_envio', models.CharField(choices=[('maritimo', 'Marítimo'), ('aereo', 'Aéreo'), ('terrestre', 'Terrestre')], default='maritimo', max_length=20)),
                ('naviera_transportista', models.CharField(blank=True, max_length=200, null=True)),
                ('fecha_embarque', models.DateField(blank=True, null=True)),
                ('fecha_arribo_estimada', models.DateField(blank=True, null=True)),
                ('puerto_embarque', models.CharField(blank=True, max_length=200, null=True)),
                ('puerto_destino', models.CharField(blank=True, max_length=200, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('comprador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exportaciones', to='beneficio.comprador')),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exportaciones_creadas', to=settings.AUTH_USER_MODEL)),
                ('mezcla', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exportaciones', to='beneficio.mezcla')),
                ('procesado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exportaciones', to='beneficio.procesado')),
                ('reproceso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exportaciones', to='beneficio.reproceso')),
            ],
            options={
                'verbose_name': 'Exportación',
                'verbose_name_plural': 'Exportaciones',
                'ordering': ['-fecha_exportacion'],
            },
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_venta', models.CharField(editable=False, max_length=50, unique=True)),
                ('fecha_venta', models.DateTimeField(default=django.utils.timezone.now)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_proceso', 'En Proceso'), ('completada', 'Completada'), ('cancelada', 'Cancelada')], default='pendiente', max_length=20)),
                ('tipo_producto', models.CharField(choices=[('procesado', 'Procesado/Trilla'), ('reproceso', 'Reproceso'), ('mezcla', 'Mezcla')], max_length=20)),
                ('peso_vendido_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precio_quintal', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio por Quintal (Q)')),
                ('precio_total', models.DecimalField(decimal_places=2, editable=False, max_digits=12)),
                ('numero_factura', models.CharField(blank=True, max_length=100, null=True)),
                ('numero_contrato', models.CharField(blank=True, max_length=100, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('fecha_entrega', models.DateField(blank=True, null=True)),
                ('transportista', models.CharField(blank=True, max_length=200, null=True)),
                ('numero_placa', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('comprador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ventas', to='beneficio.comprador')),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ventas_creadas', to=settings.AUTH_USER_MODEL)),
                ('mezcla', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ventas', to='beneficio.mezcla')),
                ('procesado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ventas', to='beneficio.procesado')),
                ('reproceso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ventas', to='beneficio.reproceso')),
            ],
            options={
                'verbose_name': 'Venta',
                'verbose_name_plural': 'Ventas',
                'ordering': ['-fecha_venta'],
            },
        ),
    ]
