# Generated by Django 5.0.1 on 2026-01-13 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficio', '0025_exportacion_venta'),
    ]

    operations = [
        migrations.AddField(
            model_name='exportacion',
            name='cantidad',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='exportacion',
            name='peso_por_unidad',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='exportacion',
            name='unidad_medida',
            field=models.CharField(choices=[('kg', 'Kilogramos'), ('gramos', 'Gramos'), ('libras', 'Libras'), ('quintales', 'Quintales'), ('bolsas', 'Bolsas'), ('sacos', 'Sacos')], default='kg', max_length=20),
        ),
        migrations.AddField(
            model_name='venta',
            name='cantidad',
            field=models.DecimalField(decimal_places=4, default=0, help_text='Cantidad vendida en la unidad seleccionada', max_digits=10),
        ),
        migrations.AddField(
            model_name='venta',
            name='peso_por_unidad',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Solo para bolsas: peso por bolsa en libras', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='venta',
            name='unidad_medida',
            field=models.CharField(choices=[('kg', 'Kilogramos'), ('gramos', 'Gramos'), ('libras', 'Libras'), ('quintales', 'Quintales'), ('bolsas', 'Bolsas'), ('sacos', 'Sacos')], default='kg', help_text='Unidad en la que se realizó la venta', max_length=20),
        ),
        migrations.AlterField(
            model_name='venta',
            name='peso_vendido_kg',
            field=models.DecimalField(decimal_places=4, help_text='Peso total vendido en kilogramos (calculado automáticamente)', max_digits=10),
        ),
    ]
