# Generated by Django 5.0.1 on 2026-01-13 14:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficio', '0026_exportacion_cantidad_exportacion_peso_por_unidad_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Partida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_partida', models.CharField(editable=False, help_text='Número único de partida (ej: P-L001-001)', max_length=50, unique=True)),
                ('tipo_cafe', models.CharField(blank=True, help_text='Tipo de café (opcional, hereda del lote si no se especifica)', max_length=100, null=True)),
                ('proveedor', models.CharField(blank=True, help_text='Proveedor de esta partida específica', max_length=200, null=True)),
                ('fecha_ingreso', models.DateTimeField(blank=True, help_text='Fecha de ingreso de la partida', null=True)),
                ('peso_bruto_kg', models.DecimalField(decimal_places=2, help_text='Peso BRUTO (con tara) en kilogramos', max_digits=10)),
                ('tara_kg', models.DecimalField(decimal_places=2, default=0, help_text='Peso de la tara (sacos, contenedores, etc.)', max_digits=10)),
                ('peso_neto_kg', models.DecimalField(decimal_places=2, editable=False, help_text='Peso NETO (sin tara) = peso_bruto - tara', max_digits=10)),
                ('unidad_peso', models.CharField(choices=[('kg', 'Kilogramos'), ('qq', 'Quintales'), ('lb', 'Libras')], default='kg', max_length=10)),
                ('humedad', models.DecimalField(blank=True, decimal_places=2, help_text='Porcentaje de humedad', max_digits=5, null=True)),
                ('numero_sacos', models.IntegerField(blank=True, help_text='Cantidad de sacos/bultos', null=True)),
                ('observaciones', models.TextField(blank=True, help_text='Notas adicionales sobre la partida', null=True)),
                ('activo', models.BooleanField(default=True, help_text='Indica si la partida está activa')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bodega', models.ForeignKey(blank=True, help_text='Bodega donde se almacena (opcional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partidas', to='beneficio.bodega')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partidas_creadas', to=settings.AUTH_USER_MODEL)),
                ('lote', models.ForeignKey(help_text='Lote al que pertenece esta partida', on_delete=django.db.models.deletion.CASCADE, related_name='partidas', to='beneficio.lote')),
            ],
            options={
                'verbose_name': 'Partida',
                'verbose_name_plural': 'Partidas',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['lote', 'numero_partida'], name='beneficio_p_lote_id_23bb1d_idx'), models.Index(fields=['created_at'], name='beneficio_p_created_d3c283_idx')],
            },
        ),
    ]
