# Generated by Django 5.0.1 on 2026-01-13 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficio', '0027_partida'),
    ]

    operations = [
        migrations.AddField(
            model_name='partida',
            name='nombre_partida',
            field=models.CharField(blank=True, help_text='Nombre o identificador personalizado de la partida (ej: Partida A, Entrega-001)', max_length=100, null=True),
        ),
    ]
