# Generated by Django 5.0.1 on 2026-01-13 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beneficio', '0028_partida_nombre_partida'),
    ]

    operations = [
    ]
