# Generated by Django 5.0.1 on 2026-01-19 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficio', '0030_auto_rename_partida_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='comprobante',
            field=models.FileField(
                blank=True,
                help_text='Comprobante de pago (foto o documento)',
                null=True,
                upload_to='comprobantes/%Y/%m/'
            ),
        ),
    ]
