# Generated by Django 5.0.1 on 2026-01-19 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficio', '0032_add_ubicacion_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='lote',
            name='percha',
            field=models.CharField(blank=True, help_text='Nombre de la percha', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='lote',
            name='fila',
            field=models.CharField(blank=True, help_text='Fila en la percha', max_length=50, null=True),
        ),
    ]
