# Generated by Django 5.0.1 on 2026-01-20 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('beneficio', '0033_lote_ubicacion_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='catacion',
            name='partida',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cataciones', to='beneficio.partida'),
        ),
        migrations.AlterField(
            model_name='catacion',
            name='tipo_muestra',
            field=models.CharField(choices=[('lote', 'Lote'), ('procesado', 'Procesado/Trilla'), ('reproceso', 'Reproceso'), ('mezcla', 'Mezcla'), ('partida', 'Partida')], max_length=20),
        ),
    ]
