# Generated by Django 5.0.1 on 2026-01-21 17:08

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficio', '0034_catacion_partida'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanillaSemanal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha Inicio de Semana')),
                ('fecha_fin', models.DateField(verbose_name='Fecha Fin de Semana')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Planilla Semanal',
                'verbose_name_plural': 'Planillas Semanales',
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='RegistroDiario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.CharField(choices=[('lunes', 'Lunes'), ('martes', 'Martes'), ('miercoles', 'Miércoles'), ('jueves', 'Jueves'), ('viernes', 'Viernes'), ('sabado', 'Sábado')], max_length=10, verbose_name='Día')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('libras_cortadas', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Libras Cortadas')),
                ('tipo_cafe_manual', models.CharField(blank=True, help_text='Si el tipo de café no está en la lista, escríbelo aquí', max_length=100, null=True, verbose_name='Tipo de Café (Manual)')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Registro Diario',
                'verbose_name_plural': 'Registros Diarios',
                'ordering': ['fecha', 'trabajador'],
            },
        ),
        migrations.CreateModel(
            name='Trabajador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=200, verbose_name='Nombre Completo')),
                ('cedula', models.CharField(blank=True, max_length=50, null=True, verbose_name='Cédula')),
                ('telefono', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Trabajador',
                'verbose_name_plural': 'Trabajadores',
                'ordering': ['nombre_completo'],
            },
        ),
        migrations.AddField(
            model_name='planillasemanal',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planillas_creadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='registrodiario',
            name='planilla',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_diarios', to='beneficio.planillasemanal', verbose_name='Planilla'),
        ),
        migrations.AddField(
            model_name='registrodiario',
            name='tipo_cafe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registros_corte', to='beneficio.tipocafe', verbose_name='Tipo de Café (Lista)'),
        ),
        migrations.AddField(
            model_name='registrodiario',
            name='trabajador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros', to='beneficio.trabajador', verbose_name='Trabajador'),
        ),
        migrations.AlterUniqueTogether(
            name='registrodiario',
            unique_together={('planilla', 'trabajador', 'dia_semana', 'fecha')},
        ),
    ]
