# Generated by Django 5.0.1 on 2026-01-21 18:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficio', '0035_add_beneficiado_finca_models'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='partida',
            name='beneficio_p_lote_id_23bb1d_idx',
        ),
        migrations.RemoveIndex(
            model_name='partida',
            name='beneficio_p_created_d3c283_idx',
        ),
        migrations.RemoveField(
            model_name='partida',
            name='nombre_partida',
        ),
        migrations.AddField(
            model_name='bodega',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='bodega',
            name='nombre',
            field=models.CharField(default='Bodega', max_length=100),
        ),
        migrations.AlterField(
            model_name='bodega',
            name='responsable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bodegas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='partida',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='partida',
            name='numero_partida',
            field=models.CharField(editable=False, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='partida',
            name='observaciones',
            field=models.TextField(blank=True, null=True),
        ),
    ]
