# Generated by Django 5.0.1 on 2026-02-02 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficio', '0038_add_inventory_tracking'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='partida',
            name='beneficio_p_lote_id_23bb1d_idx',
        ),
        migrations.RemoveIndex(
            model_name='partida',
            name='beneficio_p_created_d3c283_idx',
        ),
        migrations.RemoveField(
            model_name='partida',
            name='nombre_partida',
        ),
        migrations.AddField(
            model_name='subpartida',
            name='bz_gramos',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='B/Z en gramos', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='subpartida',
            name='bz_porcentaje',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='B/Z en porcentaje', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='subpartida',
            name='defectos_fisicos',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Defectos físicos (%)', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='subpartida',
            name='defectos_verdes',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Defectos verdes (%)', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='subpartida',
            name='granulometria',
            field=models.CharField(blank=True, help_text='Granulometría', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='subpartida',
            name='oro_limpio',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Oro limpio (peso)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='subpartida',
            name='oro_sucio',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Oro sucio (peso)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='subpartida',
            name='perfil_sensorial',
            field=models.TextField(blank=True, help_text='Perfil sensorial del café', null=True),
        ),
        migrations.AddField(
            model_name='subpartida',
            name='peso_cp',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Peso C/P', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='partida',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='partida',
            name='numero_partida',
            field=models.CharField(editable=False, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='partida',
            name='observaciones',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subpartida',
            name='fecha_ingreso',
            field=models.DateField(blank=True, help_text='Fecha del lote', null=True),
        ),
        migrations.AlterField(
            model_name='subpartida',
            name='humedad',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Porcentaje de humedad', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='subpartida',
            name='nombre',
            field=models.CharField(help_text='ID del lote (Ej: DELFINA / NANDO 3RAS)', max_length=200),
        ),
        migrations.AlterField(
            model_name='subpartida',
            name='numero_sacos',
            field=models.IntegerField(default=1, help_text='Número de sacos'),
        ),
    ]
