# Generated by Django 5.0.1 on 2026-02-02 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficio', '0039_add_catacion_fields_subpartida'),
    ]

    operations = [
        migrations.AddField(
            model_name='subpartida',
            name='etiqueta',
            field=models.CharField(blank=True, help_text='Etiqueta del lote', max_length=100, null=True),
        ),
    ]
