# Generated by Django 5.0.1 on 2026-02-02 22:02

from django.db import migrations, models


def crear_etiquetas_iniciales(apps, schema_editor):
    """Crear etiquetas predefinidas"""
    EtiquetaLote = apps.get_model('beneficio', 'EtiquetaLote')
    etiquetas = [
        'Compra Geisha',
        'Natural Geisha Finca',
        'Natural 2SL28 Finca',
        'Catuai Finca',
        'Bourbon Finca',
        'Caturra Finca',
        'Pacamara Finca',
        'SL28 Lavado',
        'Geisha Honey',
        'Lote Especial',
    ]
    for nombre in etiquetas:
        EtiquetaLote.objects.get_or_create(nombre=nombre)


class Migration(migrations.Migration):

    dependencies = [
        ('beneficio', '0040_add_etiqueta_to_subpartida'),
    ]

    operations = [
        migrations.CreateModel(
            name='EtiquetaLote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Etiqueta de Lote',
                'verbose_name_plural': 'Etiquetas de Lote',
                'db_table': 'etiquetas_lote',
                'ordering': ['nombre'],
            },
        ),
        migrations.RunPython(crear_etiquetas_iniciales, migrations.RunPython.noop),
    ]
